version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: /bin/bash -c "pip install -r requirements.txt && exec invoke run_dev"
    volumes:
      - .:/worktask
    ports:
      - "8000:8000"
    depends_on:
      - db
