db:
  image: postgres:9.6
  environment:
    - POSTGRES_USER=postgres
  volumes:
    - ./:/web

django:
  image: adolgarev/python2:1473852567
  volumes:
    - ./:/web
  working_dir: /web
  links:
    - db:db
  expose:
    - "9000"
  ports:
    - "9000:9000"
  environment:
    - DJANGO_SETTINGS_MODULE=worktask.settings
  command: /bin/bash -c "pip install -r requirements.txt && exec invoke run_dev"
