# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 09:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout_accept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)])),
            ],
        ),
        migrations.CreateModel(
            name='Sell_types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Per_count',
            fields=[
                ('good', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='market.Goods')),
                ('discount_quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price_quantity', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)])),
            ],
        ),
        migrations.CreateModel(
            name='Per_kg',
            fields=[
                ('good', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='market.Goods')),
                ('discount_kg', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)])),
                ('price_kg', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)])),
            ],
        ),
        migrations.CreateModel(
            name='Smth_free',
            fields=[
                ('good', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='smth_good', serialize=False, to='market.Goods')),
                ('quantity_to_get', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('item_quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='sell_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Sell_types'),
        ),
        migrations.AddField(
            model_name='checkout_accept',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Goods'),
        ),
        migrations.AddField(
            model_name='smth_free',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.Goods'),
        ),
    ]
